version=2.1.0

# The version of the MarkLogic Spark connector to be used by Flux.
connectorVersion=3.1.0

picocliVersion=4.7.7

# Aligned with our Spark connector.
sparkVersion=4.1.1
hadoopVersion=3.4.2
awssdkVersion=2.29.52
langchain4jVersion=1.11.0
tikaVersion=3.3.0

# Define these on the command line to publish to OSSRH
# See https://central.sonatype.org/publish/publish-gradle/#credentials for more information
mavenCentralUsername=
mavenCentralPassword=
mavenCentralUrl=https://oss.sonatype.org/service/local/staging/deploy/maven2/

# For publishing to internal Nexus repository
publishUrl=file:../releases

# Adding these based on the non-standard JDK locations used by Jenkins.
# See https://docs.gradle.org/current/userguide/toolchains.html#sec:custom_loc for information
# on custom toolchain locations in Gradle.
org.gradle.java.installations.fromEnv=JAVA_HOME_DIR
org.gradle.java.installations.paths=/users/ml/builder/java/jdk-11.0.2,/home/builder/java/jdk-17.0.2

# Bumping this up as with Spark 4, Gradle often runs into heap space issues when trying to build the project.
org.gradle.jvmargs=-Xmx4g






